import type { en } from "@/content/en/site";

type DictionaryShape = { [K in keyof typeof en]: unknown };

export const es = {
  localeName: "Español",
  skip: "Saltar al contenido",
  navigation: { label: "Navegación principal", open: "Abrir menú", close: "Cerrar menú", essence: "Esencia", menu: "Menú Restaurante", bakery: "Panadería", promotions: "Promociones y Eventos", experience: "Experiencia", visit: "Visítanos" },
  ordering: {
    cta: "Pedir para retirar",
    helper: "¿Listo para pedir? Completa tu pedido para retiro de forma segura a través de Clover.",
  },
  hero: { eyebrow: "Argentine Grill & Bakery", title: [{ text: "El sabor", style: "default" }, { text: "argentino", style: "argentina" }, { text: "empieza en", style: "gold" }, { text: "el fuego.", style: "gold" }], description: "Parrilla, panadería y café hechos con tiempo, oficio y ese espíritu que convierte cada mesa en un encuentro.", primary: "Explora el menú", secondary: "Pedir para retirar" },
  essence: { eyebrow: "Nuestra esencia", title: "Fuego, harina y tiempo.", body: "Celebramos una cocina honesta que nace de las brasas y continúa en el horno: cortes a la parrilla, empanadas, panes artesanales, café y mate para compartir.", quote: "La cocina no termina cuando sale el plato. Termina cuando la mesa se llena.", quoteBy: "Espíritu G.O.A.T. · Texto editorial pendiente de aprobación", pillars: [["Brasas", "Fuego real, tiempo preciso y sabores que hablan por sí solos."], ["Masa", "El oficio paciente de amasar, fermentar y hornear cada día."], ["Encuentro", "La mesa como lugar de pausa, conversación y comunidad."]] },
  flavours: { eyebrow: "Lo que nos mueve", title: "Sabores con historia.", body: "De las brasas al horno, una mesa argentina donde hay lugar para todos.", items: ["Parrilla", "Empanadas", "Panadería", "Café y mate"] },
  story: { eyebrow: "Una mesa para compartir", title: "Tradición argentina, servida a nuestra manera.", body: "G.O.A.T. reúne el carácter de la parrilla con la calidez de una panadería de barrio. Cada detalle invita a bajar el ritmo, comer bien y sentirse parte." },
  promotions: { eyebrow: "Lo que está pasando", title: "Promociones y eventos.", viewAll: "Ver todo", empty: "No hay promociones ni eventos activos en este momento.", promotion: "Promoción", event: "Evento" },
  visit: { eyebrow: "Ven a conocernos", title: "Tu lugar en la mesa.", address: "Dirección", hours: "Horarios", contact: "Contacto", pending: "Pendiente de confirmación del cliente." },
  contact: { title: "Contáctanos", intro: "Envíanos un mensaje y nuestro equipo responderá lo antes posible.", name: "Nombre", email: "Correo electrónico", phone: "Teléfono (opcional)", subject: "Asunto", message: "Mensaje", consent: "Acepto que G.O.A.T. use estos datos para responder mi consulta.", submit: "Enviar mensaje", sending: "Enviando…", success: "Gracias, tu mensaje fue enviado.", genericError: "No pudimos enviar tu mensaje. Inténtalo nuevamente.", configError: "El correo de contacto aún no está configurado.", validation: "Revisa los campos indicados.", subjectOptions: ["Consulta general", "Evento privado", "Panadería", "Otro"] },
  menu: { eyebrow: "La carta G.O.A.T.", title: "Menú restaurante", intro: "Explora nuestra selección actual. Los productos y precios fueron transcritos del PDF del cliente y pueden cambiar.", logoAlt: "Logo oficial de G.O.A.T. Argentine Grill & Bakery", restaurant: "Restaurante", bakery: "Panadería", index: "Ver categorías", pdf: "Ver / Descargar PDF", share: "Compartir menú", shared: "Enlace copiado", qrTitle: "Escanea para ver el menú", qrBody: "Abre la carta directamente en tu teléfono.", qrAlt: "Código QR para abrir la carta web de G.O.A.T.", qrDevelopment: "Solo desarrollo: este QR usa la URL provisional del sitio.", bakeryTitle: "Selección de panadería", bakeryBody: "Estamos preparando nuestro catálogo de panadería. Publicaremos aquí la selección confirmada próximamente.", provisional: "Traducción pendiente de aprobación del cliente" },
  footer: { description: "Parrilla argentina, panadería artesanal y café. Una mesa hecha para compartir.", explore: "Explora", connect: "Conecta", socialsPending: "Redes sociales próximamente.", back: "Volver arriba" },
  metadata: { homeTitle: "Parrilla Argentina y Panadería", homeDescription: "Parrilla argentina, panadería artesanal y café hechos para compartir.", menuTitle: "Menú Restaurante", menuDescription: "Explora la carta de G.O.A.T.: entradas, carnes a la parrilla, pastas, postres y bebidas.", promotionsTitle: "Promociones y Eventos", promotionsDescription: "Descubre promociones activas y próximos eventos de G.O.A.T. Argentine Grill & Bakery." },
} as const satisfies DictionaryShape;
