export const en = {
  localeName: "English",
  skip: "Skip to content",
  navigation: {
    label: "Main navigation",
    open: "Open menu",
    close: "Close menu",
    essence: "Essence",
    menu: "Restaurant Menu",
    bakery: "Bakery",
    promotions: "Promotions & Events",
    experience: "Experience",
    visit: "Visit Us",
  },
  reservation: "Reserve Your Table",
  hero: {
    eyebrow: "Argentine Grill & Bakery",
    title: [
      { text: "Argentine", style: "argentina" },
      { text: "flavour", style: "default" },
      { text: "starts with", style: "gold" },
      { text: "fire.", style: "gold" },
    ],
    description: "Grill, bakery and coffee made with time, craft and the spirit that turns every table into a gathering.",
    primary: "Explore our menu",
    secondary: "Plan your visit",
  },
  essence: {
    eyebrow: "Our essence",
    title: "Fire, flour and time.",
    body: "We celebrate honest cooking that begins over the coals and continues in the oven — grilled cuts, empanadas, artisan bread, coffee and mate made for sharing.",
    quote: "Cooking does not end when the plate leaves the kitchen. It ends when the table fills up.",
    quoteBy: "G.O.A.T. spirit · Editorial copy pending approval",
    pillars: [
      ["Embers", "Real fire, precise timing and flavours that speak for themselves."],
      ["Dough", "The patient craft of kneading, fermenting and baking every day."],
      ["Gathering", "The table as a place for pause, conversation and community."],
    ],
  },
  flavours: { eyebrow: "What moves us", title: "Flavours with a story.", body: "From grill to oven, an Argentine table with room for everyone.", items: ["Grill", "Empanadas", "Bakery", "Coffee & mate"] },
  story: { eyebrow: "A table to share", title: "Argentine tradition, served our way.", body: "G.O.A.T. brings the character of the grill together with the warmth of a neighbourhood bakery. Every detail invites you to slow down, eat well and feel at home." },
  promotions: { eyebrow: "What is happening", title: "Promotions & events.", viewAll: "See all", empty: "No active promotions or events right now.", promotion: "Promotion", event: "Event" },
  visit: { eyebrow: "Come meet us", title: "Your place at the table.", address: "Address", hours: "Hours", contact: "Contact", pending: "To be confirmed by the client." },
  contact: { title: "Contact us", intro: "Send us a message and our team will reply as soon as possible.", name: "Name", email: "Email", phone: "Phone (optional)", subject: "Subject", message: "Message", consent: "I agree that G.O.A.T. may use these details to answer my inquiry.", submit: "Send message", sending: "Sending…", success: "Thanks — your message was sent.", genericError: "We could not send your message. Please try again.", configError: "Contact email is not configured yet.", validation: "Please review the highlighted fields.", subjectOptions: ["General inquiry", "Private event", "Bakery", "Other"] },
  menu: { eyebrow: "The G.O.A.T. menu", title: "Restaurant menu", intro: "Explore our current selection. Items and prices are transcribed from the client PDF and may change.", logoAlt: "G.O.A.T. Argentine Grill & Bakery official logo", restaurant: "Restaurant", bakery: "Bakery", index: "Browse categories", pdf: "View / Download PDF", share: "Share menu", shared: "Link copied", qrTitle: "Scan to view the menu", qrBody: "Open the menu directly on your phone.", qrAlt: "QR code to open the G.O.A.T. web menu", qrDevelopment: "Development only: this QR uses the provisional site URL.", bakeryTitle: "Bakery selection", bakeryBody: "Our bakery catalogue is being prepared. We will publish the confirmed selection here soon.", provisional: "Translation pending client approval" },
  footer: { description: "Argentine grill, artisan bakery and coffee. A table made for sharing.", explore: "Explore", connect: "Connect", socialsPending: "Social links coming soon.", back: "Back to top" },
  metadata: { homeTitle: "Argentine Grill & Bakery", homeDescription: "Argentine grill, artisan bakery and coffee made for sharing.", menuTitle: "Restaurant Menu", menuDescription: "Explore the G.O.A.T. restaurant menu, from appetizers and grilled meats to pasta, desserts and drinks.", promotionsTitle: "Promotions & Events", promotionsDescription: "Discover active promotions and upcoming events at G.O.A.T. Argentine Grill & Bakery." },
} as const;
